global:
  scrape_interval: "15s"

scrape_configs:
  - job_name: "fastapi_app"
    scrape_interval: "5s"
    static_configs:
      - targets: ["app:8000"] # ''app'' is the service name defined in docker-compose.yml
