name: CI/CD Pipeline - SaveinCloud

on:
  push:
    branches: [ "main" ] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Download from repository
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. DockerHub Login (Using Github Secrets for security)
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Create the Docker image and push to DockerHub
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        # Using the tag latest for Jelastic and a unique tag with the commit SHA for versioning
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/jelastic-demo:latest
          ${{ secrets.DOCKER_USERNAME }}/jelastic-demo:${{ github.sha }}

    # 4. Warns SaveinCloud about the new image and triggers redeploy via Jelastic API
    - name: Deploy to SaveinCloud
      run: |
        echo "Iniciando Redeploy..."
        
        # Armazena a resposta em uma variável
        RESPONSE=$(curl -s -X POST "https://app.paas.saveincloud.net.br/1.0/environment/control/rest/redeploycontainersbygroup" \
          -d "session=${{ secrets.JELASTIC_TOKEN }}" \
          -d "envName=${{ secrets.ENV_NAME }}" \
          -d "nodeGroup=cp" \
          -d "tag=latest" \
          -d "useExistingVolumes=true")
        
        echo "Resposta da Plataforma: $RESPONSE"
        
        # Verifica se tem a palavra "error" ou se "result" é diferente de 0
        if [[ "$RESPONSE" == *"error"* ]] || [[ "$RESPONSE" != *"\"result\":0"* ]]; then
          echo "❌ ERRO NO DEPLOY! O ambiente não foi atualizado."
          exit 1
        else
          echo "✅ Deploy realizado com sucesso!"
        fi