name: CI/CD Pipeline - SaveinCloud

on:
  push:
    branches: [ "main" ] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Download from repository
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. DockerHub Login (Using Github Secrets for security)
    - name: Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Create the Docker image and push to DockerHub
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        # Using the tag latest for Jelastic and a unique tag with the commit SHA for versioning
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/jelastic-demo:latest
          ${{ secrets.DOCKER_USERNAME }}/jelastic-demo:${{ github.sha }}

    # 4. Warns SaveinCloud about the new image and triggers redeploy via Jelastic API
    - name: Saveincloud Deploy
      run: |
        echo "Starting Redeploy..."
        
        # Store the response from Jelastic API
        RESPONSE=$(curl -s -X POST "https://app.paas.saveincloud.net.br/1.0/environment/control/rest/redeploycontainersbygroup" \
          -d "session=${{ secrets.JELASTIC_TOKEN }}" \
          -d "envName=${{ secrets.ENV_NAME }}" \
          -d "nodeGroup=cp" \
          -d "tag=latest" \
          -d "useExistingVolumes=true")
        
        echo "Jelastic Response: $RESPONSE"

        # Parse the result code from the response using jq
        RESULT_CODE=$(echo "$RESPONSE" | jq '.result')
        
        # Check if the “result” is different from 0 (which indicates failure)
        if [ "$RESULT_CODE" != "0" ]; then
          echo "Error, API returned $RESULT_CODE"
          exit 1
        else
          echo "Sucess: Deployment completed (Code 0))"
        fi