name: CI/CD Pipeline - SaveinCloud

on:
  push:
    branches: [ "main" ] # Dispara sempre que tiver push na main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Baixa o código do seu repositório
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Faz login no Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Cria a imagem Docker e manda pro Hub
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        # Dica Pro: Usamos a tag 'latest' E a hash do commit para histórico
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/jelastic-demo:latest
          ${{ secrets.DOCKER_USERNAME }}/jelastic-demo:${{ github.sha }}

    # 4. Mágica: Avisa a SaveinCloud para atualizar o container
    - name: Deploy to SaveinCloud
      run: |
        echo "Iniciando Redeploy na Jelastic..."
        
        # Chama a API da Jelastic para redeployar pelo Grupo de Nós (cp = compute/app)
        curl -X POST "https://app.paas.saveincloud.net.br/1.0/environment/control/rest/redeploycontainersbygroup" \
          -d "session=${{ secrets.JELASTIC_TOKEN }}" \
          -d "envName=${{ secrets.ENV_NAME }}" \
          -d "nodeGroup=cp" \
          -d "tag=latest" \
          -d "useExistingVolumes=true"